### ISSUE TITLE
Is this plugin abandoned

### ISSUE THREAD

**Issue by boskokg** [crazecoder/open_file#198]
Simes like this plugin is abandoned. Does anyone have suggestion for an alternative?

Thanks in advance

**Comment by arielsoriano** [comment]
I think so :S 
I'm also looking for an alternative. I just can't open files in flutter.

**Comment by in-emilio** [comment]
Did you find any other alternatives?

**Comment by GoldenSoju** [comment]
I created an updated fork with 
- updated ffi dependency (2.0.1)
- removed REQUEST_INSTALL_PACKAGES permission
- embedding 2 (Android)
- and other smaller updates

You can use it via:

```yaml
  open_filex:
    git:
      url: https://github.com/GoldenSoju/open_file.git
```

The package could need a complete rehaul...but well, for the moment the updated fork should work.
