### ISSUE TITLE
upgrade ffi to version 2.x

### ISSUE THREAD

**Issue by SimonHausdorf** [crazecoder/open_file#200]
Can we upgrade ffi?

**Comment by GoldenSoju** [comment]
I created an updated fork with 
- updated ffi dependency (2.0.1)
- removed REQUEST_INSTALL_PACKAGES permission
- embedding 2 (Android)
- and other smaller updates

You can use it via:

```yaml
  open_filex:
    git:
      url: https://github.com/GoldenSoju/open_file.git
```
