### ISSUE TITLE
conflict between open file and matrix sdk 

### ISSUE THREAD

**Issue by ialyzaafan** [crazecoder/open_file#215]
Because no versions of open_file match >3.2.1 <4.0.0 and open_file 3.2.1 depends on ffi ^1.0.0, open_file ^3.2.1 requires ffi ^1.0.0.
And because matrix >=0.13.0 depends on ffi ^2.0.0, open_file ^3.2.1 is incompatible with matrix >=0.13.0.

**Comment by nilsreichardt** [comment]
I think this sould work as workaround, when you use the `main` branch in your `pubspec.yaml` instead of a version:

```yaml
open_file:
    git:
      url: https://github.com/crazecoder/open_file
```
