### ISSUE TITLE
conflict between open_file and file_picker

### ISSUE THREAD

**Issue by yusufziyayerebakan** [crazecoder/open_file#218]
Because open_file >=3.1.0 depends on ffi ^1.0.0 and file_picker 5.2.0+1 depends on ffi ^2.0.1, open_file >=3.1.0 is incompatible with file_picker 5.2.0+1.
And because no versions of file_picker match >5.2.0+1 <6.0.0, open_file >=3.1.0 is incompatible with file_picker ^5.2.0+1.
So, because hmc_sms_mobile depends on both file_picker ^5.2.0+1 and open_file ^3.2.1, version solving failed.
pub get failed (1; So, because hmc_sms_mobile depends on both file_picker ^5.2.0+1 and open_file ^3.2.1, version solving failed.)

**Comment by nilsreichardt** [comment]
This works as a workaround:

```yaml
file_picker: ^5.2.0+1
open_file:
  git:
    url: https://github.com/crazecoder/open_file
```
