### ISSUE TITLE
please remove REQUEST_INSTALL_PACKAGES due google playstore policy

### ISSUE THREAD

**Issue by eggysudianto** [crazecoder/open_file#221]
![image](https://user-images.githubusercontent.com/16233241/196897868-4c47170b-2c40-4a36-9afb-2014a8e248ce.png)

**Comment by EyyupA** [comment]
I have the same problem.

**Comment by EyyupA** [comment]
I have already switch to [open_filex](https://pub.dev/packages/open_filex) and also [open_file_safe](https://pub.dev/packages/open_file_safe), but both times it was rejected. 

https://i.imgur.com/vmBkGUW.png

My pubspec.yml
```YML
name: ******
description: ******

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.2+37

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  provider: ^6.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.8
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  permission_handler: ^8.3.0
  open_filex: ^4.1.1
  path_provider: ^2.0.8
  animations: ^2.0.2
  socket_io_client: 2.0.0-beta.3-nullsafety.0
  flutter_slidable: ^2.0.0
  flutter_markdown: ^0.6.9+1
  markdown: ^4.0.1
  dropdown_search: ^5.0.2
  json_patch: ^3.0.0
  month_picker_dialog_2: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.4
  build_runner: ^2.0.0 #for: json_serializable
  rename: ^2.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - src/program.png
    - src/images/User.png
    - src/images/Key.png
    - src/images/Folder.png
    - src/images/Letter.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_icons:
  image_path: "src/app_logo/4x4_black@1024.png" 
  android: true
  ios: true
  remove_alpha_ios: true

```
