### ISSUE TITLE
open_file 3.2.1 depends on ffi ^1.0.0

### ISSUE THREAD

**Issue by sgehrman** [crazecoder/open_file#242]
update packages

**Comment by Becca-Saka** [comment]
@sgehrman  you use the latest commit, works for me.

**Comment by nilsreichardt** [comment]
As @Becca-Saka suggested, you can use the latest commit. You can do this by using this in your `pubspec.yaml`:

```yaml
open_file:
  git:
    url: https://github.com/crazecoder/open_file
```
